apiVersion: v1
kind: Service
metadata:
  name: ducklake-backend-service
  labels:
    app: ducklake-backend
spec:
  selector:
    app: ducklake-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP # Use ClusterIP for internal access, LoadBalancer for external
