
apiVersion: apps/v1
kind: Deployment
metadata:
  name: marimo-deployment
  labels:
    app: marimo
    component: notebook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marimo
  template:
    metadata:
      labels:
        app: marimo
        component: notebook
    spec:
      containers:
      - name: marimo
        image: your-registry/datlake-marimo:latest
        ports:
        - containerPort: 2718
          name: http
        env:
        - name: MARIMO_HOST
          value: "0.0.0.0"
        - name: MARIMO_PORT
          value: "2718"
        - name: BACKEND_URL
          value: "http://backend-service:8000"
        - name: PYTHONUNBUFFERED
          value: "1"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 2718
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 2718
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
      securityContext:
        fsGroup: 1000
      restartPolicy: Always 