mode: standalone

accessKey: minioadmin
secretKey: minioadmin

service:
  type: ClusterIP

persistence:
  enabled: true
  size: 10Gi

resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "200m"
