apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
type: Opaque
data:
  accesskey: bWluaW9hZG1pbg== # base64 encoded 'minioadmin'
  secretkey: bWluaWFlYWRtaW4= # base64 encoded 'minioadmin'
