apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: default
  labels:
    app: ducklake
    component: database
type: Opaque
data:
  # Base64 encoded values
  # To encode: echo -n "your-value" | base64
  username: cG9zdGdyZXM=  # base64 encoded 'postgres'
  password: cG9zdGdyZXM=  # base64 encoded 'postgres' - CHANGE THIS IN PRODUCTION!
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: default
  labels:
    app: ducklake
    component: storage
type: Opaque
data:
  # Base64 encoded values
  # To encode: echo -n "your-value" | base64
  accesskey: bWluaW9hZG1pbg==  # base64 encoded 'minioadmin'
  secretkey: bWluaW9hZG1pbg==  # base64 encoded 'minioadmin' - CHANGE THIS IN PRODUCTION! 